<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>AMCClicker.Program</StartupObject>
    <AssemblyName>AMCClicker</AssemblyName>
    <RootNamespace>AMCClicker</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
